#ifndef IMAGE_VERSION_H

#define VER_PRODUCTVERSION 0, 0, 0, 0
#define VER_PRODUCTVERSION_STR "0.0\0"

#define VER_FILEVERSION 0, 0, 0, 0
#define VER_FILEVERSION_STR "0.0.0.0\0"

#define IMAGE_VERSION_H
#endif
